[
<#list fields as field>
    <#if field_index == 0>
    <#else>
    ,
    </#if>
    {
        "type": "metaField",
        "name": "${field.name}",
        "fieldType": "string",
        "objectName": "${objectName}",
        "parentid": "${parentId}",
        "label": "${field.description}",
        "controllerName": "MetaInput",
        "appid": "${appId}",
        "referenceEntity": "",
        "referenceCode": "",
        "referenceName": "",
        "enumCategory": "",
        "category": "user",
        "defaultValue": "",
        "length": "",
        "digits": "",
        "scale": "",
        "referenceTargetField": "",
        "referenceTo": "",
        "relationshipName": "",
        "relationshipOrder": "",
        "defaultValueFormula": "",
        "unique": "",
        "isExternalId": "",
        "index": "",
        "byteLength": "",
        "description": "",
        "inlineHelpText": "",
        "aggregatable": "",
        "autoNumber": "",
        "calculated": "",
        "calculatedFormula": "",
        "cascadeDelete": "",
        "caseSensitive": "",
        "createable": "",
        "custom": "",
        "defaultedOnCreate": "",
        "dependentPicklist": "",
        "picklistValues": "",
        "sortable": "",
        "isRequired": "",
        "deprecatedAndHidden": "",
        "highScaleNumber": "",
        "displayLocationInDecimal": "",
        "encrypted": "",
        "extraTypeInfo": "",
        "filterable": "",
        "filteredLookupInfo": "",
        "groupable": "",
        "htmlFormatted": "",
        "idLookup": "",
        "mask": "",
        "maskType": "",
        "nameField": "",
        "namePointing": "",
        "nillable": "",
        "permissionable": "",
        "precision": "",
        "queryByDistance": "",
        "restrictedDelete": "",
        "restrictedPicklist": "",
        "soapType": "",
        "updateable": "",
        "writeRequiresMasterRead": ""
    }
</#list>
]